<?xml version="1.0"?>

<robot name="scout_v2"  xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="robot_namespace" default="/" /> 

    <!-- 属性封装 -->
    <xacro:property name="M_PI" value="3.14159"/>

    <xacro:property name="base_x_size" value="0.9250000" />
    <xacro:property name="base_y_size" value="0.380000" />
    <xacro:property name="base_z_size" value="0.210000" />

    <xacro:property name="wheelbase" value="0.498" />
    <xacro:property name="track" value="0.58306" />   <!-- track————车轮间距 -->
    <xacro:property name="wheel_vertical_offset" value="-0.0702" />

    <xacro:property name="wheel_length" value="1.1653e-01" />
    <xacro:property name="wheel_radius" value="1.6459e-01" />

    
    <xacro:arg name="organize_cloud" default="true"/>
    <xacro:property name="organize_cloud" value="$(arg organize_cloud)" />
    
    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0" />
    </material>
    
    <!-- 底盘的轮子 -->
    <xacro:include filename="$(find scout_gazebo)/urdf/scout_wheel_type1.xacro" />
    <xacro:include filename="$(find scout_gazebo)/urdf/scout_wheel_type2.xacro" />
    <xacro:include filename="$(find scout_gazebo)/urdf/inertial.xacro" />
    <!-- <xacro:include filename="$(find scout_gazebo)/urdf/camera.xacro" /> -->
    <!-- <xacro:include filename="$(find scout_gazebo)/urdf/sensor_camera.xacro" /> -->
    
    <!-- D435i RGB-D相机相关 -->
    <!-- <xacro:include filename="$(find realsense_ros_gazebo)/xacro/depthcam.xacro"/>
    <xacro:realsense_d435 sensor_name="camera" parent_link="base_link" rate="30.0">
    <origin rpy="0 0 0" xyz="0 0 0.3"/>
    </xacro:realsense_d435> -->
    
    <!-- VLP16 激光雷达 -->
    <xacro:include filename="$(find scout_gazebo)/urdf/laser_support.xacro" />
    <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>

 <!-- 电机连接基座 -->
    <link name="motor_base">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.04" length="0.05"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.04" length="0.05"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.2"/>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
        </inertial>
    </link>

    <!-- 电机基座到支撑架的连接 -->
    <joint name="motor_base_joint" type="fixed">
        <parent link="support"/>
        <child link="motor_base"/>
        <origin xyz="0 0 0.025" rpy="0 0 0"/>
    </joint>

    <!-- 旋转平台 - 这是实际旋转的部分 -->
    <link name="velodyne_rotation_base">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.03" length="0.02"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                 <cylinder radius="0.03" length="0.02"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1"/>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
        </inertial>
    </link>

    <!-- 电机旋转关节 - 绕倾斜轴旋转 -->
    <joint name="velodyne_rotation_joint" type="continuous">
        <parent link="motor_base"/>
        <child link="velodyne_rotation_base"/>
        <origin xyz="0 0 0.035" rpy="0 0 0"/>
        <!-- 旋转轴：与垂直向下成120度夹角 -->
        <axis xyz="0.866 0 0.5"/>
    </joint>

    <!-- 连接手把/连接杆 -->
    <link name="velodyne_connecting_rod">
        <visual>
            <origin xyz="0.035 0 0.02" rpy="0 1.047 0" />
            <geometry>
                <!-- 圆柱形连接杆，沿着倾斜方向 -->
                <cylinder radius="0.008" length="0.08"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.035 0 0.02" rpy="0 1.047 0" />
            <geometry>
                <cylinder radius="0.008" length="0.08"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.02"/>
            <origin xyz="0.035 0 0.02" rpy="0 1.047 0" />
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </link>

    <!-- 连接杆到旋转基座的连接 -->
    <joint name="connecting_rod_joint" type="fixed">
        <parent link="velodyne_rotation_base"/>
        <child link="velodyne_connecting_rod"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <!-- Velodyne安装支架 - 安装在连接杆末端 -->
    <link name="velodyne_mount">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.025" length="0.015"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.025" length="0.015"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.05"/>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
    </link>

    <!-- 安装支架连接到连接杆末端 -->
    <joint name="mount_joint" type="fixed">
        <parent link="velodyne_connecting_rod"/>
        <child link="velodyne_mount"/>
        <!-- 安装在连接杆的末端位置 -->
        <origin xyz="0.07 0 0.04" rpy="0 -1.047 0"/>
    </joint>

    <!-- Velodyne激光雷达安装在支架上 -->
    <xacro:VLP-16 parent="velodyne_mount" name="velodyne" topic="/velodyne_points" organize_cloud="${organize_cloud}" hz="10" samples="440">
          <origin xyz="0 0 0.04" rpy="0 0 0" />
    </xacro:VLP-16>

    <transmission name="velodyne_rotation_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="velodyne_rotation_joint">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="velodyne_motor">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <!-- Gazebo控制器插件 -->
    <gazebo>
      <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
         <robotNamespace>/scout_v2</robotNamespace>
        <controlPeriod>0.01</controlPeriod>
        <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
      </plugin>
    </gazebo>


    <!-- IMU 模块 -->
    <xacro:include filename="$(find scout_gazebo)/urdf/imu.xacro"/>
    <xacro:imu sensor_name="imu" parent_link="base_link">
    <origin rpy="0 0 0" xyz="-0.03 0 ${base_z_size/2}"/>
    </xacro:imu>

    <!-- 机器人导航控制模块 -->
    <xacro:include filename="$(find scout_gazebo)/urdf/move.xacro" />

    <!-- Base link  底盘 -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <!--<box size="${base_x_size} ${base_y_size} ${base_z_size}"/>-->
                <mesh filename="package://scout_gazebo/meshes/base_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0.0008" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
            </geometry>
        </collision>
    </link>

    <link name="base_footprint"/>
    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="base_footprint" />
    </joint>

    <link name="inertial_link">
        <inertial>
            <mass value="40" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <!-- 宏  Scout wheel macros -->
    <!-- wheel labeled from 0 to 3, conter-clockwise, starting from front right wheel -->
    <!-- motor 1 and 2 (left side) are mechanically installed in a reversed direction -->
    <xacro:scout_wheel_type1 wheel_prefix="front_right">
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
    </xacro:scout_wheel_type1>
    <xacro:scout_wheel_type2 wheel_prefix="front_left">
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:scout_wheel_type2>
    <xacro:scout_wheel_type1 wheel_prefix="rear_left">
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:scout_wheel_type1>
    <xacro:scout_wheel_type2 wheel_prefix="rear_right">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
    </xacro:scout_wheel_type2>
</robot>
